version: "2"

formatters:
  enable:
    - gci

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/boyvinall/certificate-utils)

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

  settings:
    errcheck:
      exclude-functions:
        - (*github.com/fatih/color.Color).Printf
        - (*github.com/fatih/color.Color).Println
